### ISSUE TITLE
Address reanimated API misuse warnings that pop up starting with reanimated 3.16.0

### ISSUE THREAD

**Issue by vestrelatlassian** [gorhom/react-native-scroll-bottom-sheet#1983]
### Version

v5

### Reanimated Version

v3

### Gesture Handler Version

v2

### Platforms

iOS, Android

### What happened?

Reanimated version [3.16.0](https://github.com/software-mansion/react-native-reanimated/releases/tag/3.16.0) introduced a logger that by default shows warnings about API misuse.

![Screenshot 2024-10-17 at 3 49 45 PM](https://github.com/user-attachments/assets/59f0f765-35cd-4530-aa97-e54b9183caa6)

We are currently using bottom sheet version `5.0.2` in our app and noticed warnings started to pop up whenever the bottom sheet is rendered/re-rendered.

![Screenshot 2024-10-17 at 3 38 01 PM](https://github.com/user-attachments/assets/9d377915-4965-4708-9ff2-96c9d336cd6c)

### Reproduction steps

1. Upgrade reanimated lib to version [3.16.0](https://github.com/software-mansion/react-native-reanimated/releases/tag/3.16.0) or newer.
2. Render bottom sheet.

### Reproduction sample

https://snack.expo.dev/IUep5KqJQjKmj-dPQdc3g

### Relevant log output

```shell
If you don't want to see this message, you can disable the `strict` mode. Refer to:
https://docs.swmansion.com/react-native-reanimated/docs/debugging/logger-configuration for more details.

(NOBRIDGE) WARN  [Reanimated] Reading from `value` during component render. Please ensure that you do not access the `value` property or use `get` method of a shared value while React is rendering a component.
```

**Comment by nicolaslevavasseursmile** [comment]
Same here

**Comment by ghost** [comment]
I am also facing this issue 

![Screenshot 2024-10-18 at 4 07 31 PM](https://github.com/user-attachments/assets/f0a32d0f-ffcd-44d8-bb09-5a57f48e2ccb)

**Comment by FernandoAOborges** [comment]
same for me. 
<img src="https://github.com/user-attachments/assets/dbc12d53-18b6-4ccf-81b3-36dec2e92487" width="200" />

To resolve this for now, create a file named **reanimatedConfig.js** at the root of your project, then import it in App.tsx.

```
import {
  configureReanimatedLogger,
  ReanimatedLogLevel,
} from 'react-native-reanimated';

configureReanimatedLogger({
  level: ReanimatedLogLevel.warn, 
  strict: false,  // Disable strict mode
});
```

Import this file at the beginning of your App.tsx to apply the configuration:

```
import './reanimatedConfig';

// Rest of your code

```

**Comment by gorhom** [comment]
i tested the library on RN75 with REA [3.16.0](https://github.com/software-mansion/react-native-reanimated/releases/tag/3.16.0), but im not getting these warnings ? any ideas

**Comment by kelechi-nwankpa** [comment]
@gorhom Thanks for the response.
I'm experiencing the same warning error as mentioned above. I'm currently using RN74 and REA 3.16.0.

Would you need any other information for further debugging? 

> i tested the library on RN75 with REA [3.16.0](https://github.com/software-mansion/react-native-reanimated/releases/tag/3.16.0), but im not getting these warnings ? any ideas

**Comment by akuul** [comment]
I was having the very same issue. It's gone now out of nowhere and trying to understand why. Thinking if this could be related to cache in any way ?.. Also RN 75

**Comment by xhrebi04** [comment]
I'm experiencing same issue. 

react-native: 0.75.4
react-native-reanimated: 3.16.0

I tried to unistall/install app, `yarn start --reset-cache` as well, but without success.

**Comment by gorhom** [comment]
i'll try to submit a new release today to remove all accessing animated values as hooks dependancies

**Comment by gorhom** [comment]
i pushed a potential fix on `v5.0.4`, could someone test it and update us here ? thanks

**Comment by kelechi-nwankpa** [comment]
@gorhom I updated the dependency from `^5.0.2` to `^5.0.4`. 

The warning seems to no longer be displaying. I think the ship worked :D . Great job

**Comment by outaTiME** [comment]
Hi @gorhom, thanks for the update. Unfortunately, the warnings persist on both platforms (Android / iOS) using react-native v0.74.5. Just to mention, the bottom sheet I’m using is in detached mode, though I’m not sure if this is related to the issue.

**Comment by efstathiosntonas** [comment]
edit: it seems that a slider I was using inside the bottom sheet was causing the error so I guess all good after upgrading to 5.0.4

~Just updated to 5.0.4 too, still getting the error.~

https://docs.swmansion.com/react-native-reanimated/docs/core/useSharedValue#remarks

from docs: 

>Don't read or modify the value of a shared value during a component's render. Access to value property or calling get/set methods is a side-effect. Triggering side-effects during render [violates the Rules of React](https://react.dev/reference/rules/components-and-hooks-must-be-pure#side-effects-must-run-outside-of-render). All reads from and writes to a shared value should happen in relevant callbacks which aren't executed during render, i.e. in useAnimatedStyle or useEffect hooks.

from my understanding (demo code):

bad:

```tsx
  const reverseAnim = scaleEmoji.value === 2 ? [2, 1, 1] : [1, 1, 2];

  const emojiAnimatedScaled = useAnimatedStyle(() => {
    return {
      transform: [
        {
          translateY: interpolate(
            scaleEmoji.value,
            [0, 1, 2],
            scaled ? [1, -3, -5] : [1, 1, 1]
          )
        },
        {
          scaleY: interpolate(
            scaleEmoji.value,
            [0, 1, 2],
            scaled ? [0, 1, 1.5] : reverseAnim
          )
        },
        {
          scaleX: interpolate(
            scaleEmoji.value,
            [0, 1, 2],
            scaled ? [0, 1, 1.5] : reverseAnim
          )
        }
      ]
    };
  }, [emojiDuration, scaleDuration, scaleEmoji, scaled]);
```

good: 

```tsx
  const emojiAnimatedScaled = useAnimatedStyle(() => {
    const reverseAnim = scaleEmoji.value === 2 ? [2, 1, 1] : [1, 1, 2]; <----- moved inside reanimated hook
    return {
      transform: [
        {
          translateY: interpolate(
            scaleEmoji.value,
            [0, 1, 2],
            scaled ? [1, -3, -5] : [1, 1, 1]
          )
        },
        {
          scaleY: interpolate(
            scaleEmoji.value,
            [0, 1, 2],
            scaled ? [0, 1, 1.5] : reverseAnim
          )
        },
        {
          scaleX: interpolate(
            scaleEmoji.value,
            [0, 1, 2],
            scaled ? [0, 1, 1.5] : reverseAnim
          )
        }
      ]
    };
  }, [emojiDuration, scaleDuration, scaleEmoji, scaled]);
```

**Comment by sladik-maksym** [comment]
> Я отправил потенциальное исправление `v5.0.4`, может ли кто-нибудь протестировать его и сообщить нам об этом здесь? Спасибо

Thank you! The warning is gone, everything works great.

**Comment by ludwighen** [comment]
I still get the warning on 5.0.4 (using BottomSheetModal) unfortunately

**Comment by Willham12** [comment]
Same issue here but it's depends on the provided child.

**Comment by virendrasingh-tech** [comment]
the warning is coming directly from reanimated 3.16, i don't have @gorhom packages still it is showing to me.

**Comment by akuul** [comment]
> the warning is coming directly from reanimated 3.16, i don't have @gorhom packages still it is showing to me.

It's probably showing because of a difference package that has the same issue.

**Comment by virendrasingh-tech** [comment]
Yeah, After i have commented some of my code i found that it's coming from react-native-pager-view

> > the warning is coming directly from reanimated 3.16, i don't have @gorhom packages still it is showing to me.
> 
> It's probably showing because of a difference package that has the same issue.

**Comment by onmotion** [comment]
I guess it came from the `BottomSheetView`

**Comment by ludwighen** [comment]
it's true that a few libraries cause this warning, I got it as well from react-native-skia for example. However I think that in 5.0.4 still not all warnings have been removed from the BottomSheet. I get the warning even in an empty bottom sheet where I'm positive I don't use any shared values or other libraries. 

I use a wrapper component but maybe some of the props / DOM helps:

```
 <BottomSheetModal
      ref={bottomSheetRef}
      enableDynamicSizing={enableDynamicSizing}
      onDismiss={onDismiss}
      onChange={onChange}
      maxDynamicContentSize={maxHeight || height * 0.85}
      animationConfigs={{ duration: 100 }}
      backdropComponent={disableBackdrop ? undefined : renderBackdrop}
      footerComponent={rightButton || customFooter ? renderFooter : undefined}
      handleIndicatorStyle={{
        backgroundColor: isDarkMode ? '#737373' : '#bbbbbb',
        width: 34,
      }}
      backgroundStyle={{
        backgroundColor: isDarkMode ? '#262626' : '#ffffff',
      }}
      snapPoints={snapPoints || undefined}
      keyboardBehavior={enableDynamicSizing ? 'interactive' : 'extend'}
    >
      {isBottomSheetScrollable ? (
        children
      ) : (
        <BottomSheetView
          enableFooterMarginAdjustment={!!(customFooter || rightButton)}
        >
          {title && (
            <Box
              borderBottomWidth={0.5}
              borderColor="$trueGray200"
              width="$full"
              height={43}
            >
              <Heading size="sm" textAlign="center" mb="$2.5" mt="$2">
                {title}
              </Heading>
            </Box>
          )}
          <View
            pb={hasBottomSafeArea ? bottom : 0}
            px={hasHorizontalPadding ? '$4' : 0}
            mb={title && isScrollable ? 43 : 0}
            flexShrink={1}
          >
            {children}
          </View>
        </BottomSheetView>
      )}
    </BottomSheetModal>
  );
  ```

**Comment by akuul** [comment]
@gorhom I have removed from BottomSheet the remaining `.value` dependencies from hooks and put the last if clause inside `useEffect`. The warning is gone, might be helpful.

```typescript
if (__DEV__) {
      print({
        component: BottomSheet.name,
        method: 'render',
        params: {
          animatedSnapPoints: animatedSnapPoints.value,
          animatedCurrentIndex: animatedCurrentIndex.value,
          providedIndex: _providedIndex,
        },
      });
    }
```

**Comment by Noitham** [comment]
Seeing the error too on `5.0.4`.

In my case, I use a `BottomSheetModal` with a `BottomSheetView` inside of it.

**Comment by onmotion** [comment]
> Seeing the error too on `5.0.4`.
> 
> In my case, I use a `BottomSheetModal` with a `BottomSheetView` inside of it.

same for me, if remove BottomSheetView the warnings are gone

**Comment by felpereira** [comment]
I am facing the same problem in the code

**Comment by rxeal** [comment]
To suppress this warning, you can disable strict mode in the logger configuration by setting strict: `false` using the `configureReanimatedLogger` function before creating any animations.

Alternatively, ensure that you read or write to shared values within relevant callbacks (like `useAnimatedStyle` or `useEffect`) rather than during the render phase.

If you are stuck, try using `react-native-reanimated@3.15.4` as a workaround.

**Comment by rupam-cc** [comment]
You can disable strict mode in the logger configuration by setting strict: `false` using the `configureReanimatedLogger` function before creating any animations.

Alternatively, ensure that you read or write to shared values within relevant callbacks (like `useAnimatedStyle` or `useEffect`) rather than during the render phase.

If you are stuck, try using `react-native-reanimated@3.15.4` as a workaround.

**Comment by vhakulinen** [comment]
FWIW, in my case the warnings were originating from our own `onLayout` callbacks.

**Comment by Willham12** [comment]
here isa fix: https://github.com/gorhom/react-native-bottom-sheet/issues/1983

**Comment by Raiden-16F7** [comment]
Im facing this issue on 5.0.4 with reanimated 3.16.1, when i press my TouchableOpacity i get the same log error

```javascript
      <BottomSheet
        ref={bottomSheetRef}
        backgroundStyle={{ backgroundColor: theme.colors.background}}
        snapPoints={snapPoints}
        index={-1}
        >
        <BottomSheetScrollView contentContainerStyle={styles.sheetContent}>
          
          <Text style={styles.heading}>Select Consultation Type</Text>
          <View style={styles.consultationContainer}>
            {consultationTypes.map((type) => (
              <TouchableOpacity
                key={type}
                style={[
                  styles.consultationButton,
                  selectedConsultation === type && styles.selectedButton,
                ]}
                onPress={() => {
                  setSelectedConsultation(type);
                }}>
                <Text
                  style={[styles.buttonText, selectedConsultation === type && styles.selectedText]}>
                  {type}
                </Text>
              </TouchableOpacity>
            ))}
          </View>
          </BottomSheetView>

```

**Comment by inthisar-hamza** [comment]
This Issue is still on version 5.0.4

`If you don't want to see this message, you can disable the `strict` mode. Refer to:
https://docs.swmansion.com/react-native-reanimated/docs/debugging/logger-configuration for more details.
 (NOBRIDGE) WARN  [Reanimated] Reading from `value` during component render. Please ensure that you do not access the `value` property or use `get` method of a shared value while React is rendering a component.`

**Comment by gorhom** [comment]
another attempt to fix the issue by @pinpong was released on `v5.0.5`

**Comment by vhakulinen** [comment]
I'm still getting warnings on which leads to this: https://github.com/gorhom/react-native-bottom-sheet/blob/4f26c7825e77ea00a227e13e64e023f6c2b1e679/src/components/bottomSheet/BottomSheet.tsx#L173-L182

The props validator is accessing the `value` property of provided snap points. I noticed (in the past) that the snap points needed to be a derived value (i.e. `useDerivedValue`) instead of plain numbers on iOS, or otherwise it would get a crash.

**Comment by outaTiME** [comment]
> another attempt to fix the issue by @pinpong was released on `v5.0.5`

After updating to version 5.0.5, the warnings disappeared for me 🎉

**Comment by vhakulinen** [comment]
Just to clearify my earlier comment: the snap points must be shared value for the warnings to appear. Using normal values as snap points does not produce any warnings.

**Comment by khushal87** [comment]
![simulator_screenshot_CDFB5FFE-D400-4F9B-9AC5-419D5AF48193](https://github.com/user-attachments/assets/78fc52b2-6c57-4671-8dda-0def1f24eeeb)
Seems to occur here as well.

**Comment by VimukthiShohan** [comment]
This Issue is still on version 5.0.6

`(NOBRIDGE) WARN  [Reanimated] Reading from `value` during component render. Please ensure that you do not access the `value` property or use `get` method of a shared value while React is rendering a component.`

`If you don't want to see this message, you can disable the `strict` mode. Refer to:`
`https://docs.swmansion.com/react-native-reanimated/docs/debugging/logger-configuration for more details.`

**Comment by rochajulian** [comment]
Any update on this?

**Comment by VimukthiShohan** [comment]
> same for me. <img alt="" width="200" src="https://private-user-images.githubusercontent.com/33990306/377976631-dbc12d53-18b6-4ccf-81b3-36dec2e92487.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMDgyMjQsIm5iZiI6MTczMzEwNzkyNCwicGF0aCI6Ii8zMzk5MDMwNi8zNzc5NzY2MzEtZGJjMTJkNTMtMThiNi00Y2NmLTgxYjMtMzZkZWMyZTkyNDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDAyNTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkOWRjZGZhNTA3MDJmMDJiNjRmMmY0NTUwMDY1OWFkM2Q2MmRlMDUyNTUyYzAyMTg2NDRhMDE5YTYxMmEzY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U0Wai15TfT3qSyHXnxrLDemjMi-CBdGqNiV67_drP1w">
> 
> To resolve this for now, create a file named **reanimatedConfig.js** at the root of your project, then import it in App.tsx.
> 
> ```
> import {
>   configureReanimatedLogger,
>   ReanimatedLogLevel,
> } from 'react-native-reanimated';
> 
> configureReanimatedLogger({
>   level: ReanimatedLogLevel.warn, 
>   strict: false,  // Disable strict mode
> });
> ```
> 
> Import this file at the beginning of your App.tsx to apply the configuration:
> 
> ```
> import './reanimatedConfig';
> 
> // Rest of your code
> ```

@rochajulian I'm using this as a temporary solution for now until they fix this with an update.

**Comment by qwalker8408** [comment]
I went from version 5 to 5.0.6 on expo 52.0.23 and react native 0.76.5 and this issue for a BottomSheet was resolved. Legend !!!!!

**Comment by youssdevx** [comment]
In my case, I just had to remove the useless dependencies when using `useAnimatedStyle`
<img width="1463" alt="Image" src="https://github.com/user-attachments/assets/8da957e4-dd4d-474c-a022-427affa4b3ec" />

And the why: 
https://docs.swmansion.com/react-native-reanimated/docs/core/useAnimatedStyle/
<img width="578" alt="Image" src="https://github.com/user-attachments/assets/11a03978-bb5d-4ad9-81a9-cdcba20e0707" />

**Comment by rochajulian** [comment]
Updating to 5.0.6 fixed it! Now i'm getting this though:

[RemoteTextInput] -[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID.
inputModality = Keyboard, inputOperation = <null selector>, customInfoType = UIEmojiSearchOperations

Though I'm not sure what it is or if it is related to this package. Any clarification would be appreciated.

**Comment by rochajulian** [comment]
> Updating to 5.0.6 fixed it! Now i'm getting this though:
> 
> [RemoteTextInput] -[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:] perform input operation requires a valid sessionID. inputModality = Keyboard, inputOperation = , customInfoType = UIEmojiSearchOperations
> 
> Though I'm not sure what it is or if it is related to this package. Any clarification would be appreciated.

Nevermind... all of the sudden the OP's logs started to come up for me again

**Comment by MoritzCooks** [comment]
I face the same issue on my iOS and Android devices. It's only appearing for `<BottomSheet>` components. Using the `<BottomSheetModal>` somehow is not throwing that warning.

I'm using the following versions (also visible in my snack):
```
"expo": "^51.0.0",
"react-native": "0.74.5",
"@gorhom/bottom-sheet": "^5.1.1",
"react-native-reanimated": "^3.16.7",
"react-native-gesture-handler": "~2.16.0",
```
The `<BottomSheet>` is working in some cases where no states are changing. Even in some cases where we have state changes I do not face issues. But in one specific case where we use the BottomSheet to change configurations using a `<Picker>`

However I'm not able to reproduce this issue in a [Snack](https://snack.expo.dev/@moritzcooks/bottom-sheet---reanimated-warning-reproduction-attempt)... I post it anyway as example so maybe someone else finds a way to reproduce it.

**Comment by moneszarrugh** [comment]
The issue still persists on the latest update "5.1.4" @gorhom

**Comment by AlixH** [comment]
Up ! :)
