### ISSUE TITLE
[v4] Setting `enableContentPanningGesture` to `false` breaks `BottomSheetScrollView`

### ISSUE THREAD

**Issue by simon-abbott** [gorhom/react-native-scroll-bottom-sheet#765]
# Bug

Setting `enableContentPanningGesture` to `false` breaks the scroll interaction with `BottomSheetScrollView`. Namely, while the user's finger is still down they can move it all they want and the content does not scroll at all, but when they release their finger the momentum is applied.

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.4   |
| react-native                                | 0.64.2  |
| react-native-reanimated            | 2.2.3   |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Make a `BottomSheet` with `enableContentPanningGesture={false}`
2. Put a `BottomSheetScrollView` in it with enough contents to make it scroll
3. Expand the sheet and try to scroll the contents

Describe what you expected to happen:

Setting `enableContentPanningGesture` to `false` should disable the ability to collapse the sheet by panning, but it should not affect scrolling the contents.

## Reproducible sample code

https://snack.expo.dev/@simon.abbott/bottom-sheet-scroll

**Comment by zakthedev** [comment]
I'm having the same issue here.

**Comment by dentep** [comment]
Same problem.

**Comment by simon-abbott** [comment]
Not fixed, don't close.

**Comment by simon-abbott** [comment]
Bump.

**Comment by simon-abbott** [comment]
Bump!

**Comment by DominykasDriu** [comment]
Having the same issue with date picker inside the pan modal. It seems to close the modal when scrolling anywhere outside scrollable contents. Even when `enablePanDownToClose` is set to `false`.

**Comment by DominykasDriu** [comment]
@simon-abbott hey, I had a similar issue with a date picker inside modal. I solved the issue by using `BottomSheetView` and inside it using `ScrollView` from `react-native-gesture-handler`

`import { ScrollView } from 'react-native-gesture-handler';`

`<BottomSheetView>
    <ScrollView>
       {contents}
    </ScrollView>
</BottomSheetView>`

**Comment by simon-abbott** [comment]
Using a different `ScrollView` does work, but the problem is that I need to be able to set `enableContentPanningGesture` dynamically, and when it's enabled I need to use a `BottomSheetScrollView` so the drag-to-close works as expected. I can swap between the two dynamically based on whether or not the sheet should be enabled, but swapping out the components loses the scroll amount (snaps back to top), and I couldn't find a clean (and performant) way to preserve the scroll offset through that transition.

**Comment by simon-abbott** [comment]
Not fixed, don't close!

**Comment by simon-abbott** [comment]
bump

**Comment by simon-abbott** [comment]
bumpity bump

**Comment by simon-abbott** [comment]
bump

**Comment by simon-abbott** [comment]
Commenting to keep open

**Comment by lucarducci** [comment]
same problem here too

**Comment by cuanclifford** [comment]
please fix this

**Comment by AliMSbaee** [comment]
Same!

**Comment by AliMSbaee** [comment]
Same!

**Comment by AliMSbaee** [comment]
Pump

**Comment by simon-abbott** [comment]
Still a problem, do not close.

**Comment by keithluchtel** [comment]
@simon-abbott I ran into as similar issue and ended up doing:

```
      enablePanDownToClose={false}
      enableOverDrag={false}>
```

**Comment by simon-abbott** [comment]
Not fixed yet!

**Comment by Zakyyy** [comment]
any solution

**Comment by keithluchtel** [comment]
@Zakyyy Does the alternative I posted above work?

https://github.com/gorhom/react-native-bottom-sheet/issues/765#issuecomment-1399311529

**Comment by Zakyyy** [comment]
@keithluchtel the thing is I don't want to remove this behavior from the modal, I want to have this enabled

Do you have any other solution?

Thanks for helping

**Comment by keithluchtel** [comment]
@Zakyyy, I hadn't looked any further into it since after I used this alternative in my project. Sorry I can't be more help.

**Comment by Zakyyy** [comment]
> @Zakyyy, I hadn't looked any further into it since after I used this alternative in my project. Sorry I can't be more help.

No worries thanks

**Comment by simon-abbott** [comment]
Not fixed, don't close please.

**Comment by Yassdrk** [comment]
I have the same issue. Please help.

**Comment by mobinni** [comment]
Running into the same issue here

**Comment by khadkamonsoon** [comment]
Same problem .

**Comment by khadkamonsoon** [comment]
For now, I made margin of 2 and removed enableContentPanningGesture={false} such that user is allowed to navigate back to previous page and also have scroll function but still it is just a work around, I did such for a solution but couldn't find it.

**Comment by simon-abbott** [comment]
Not stale, please don't close.

**Comment by simon-abbott** [comment]
Still not fixed.

**Comment by NicholasBoccuzzi** [comment]
Hopping in here -- this is still an issue

**Comment by Alsania14** [comment]
Help

**Comment by ajimae** [comment]
I am also experiencing this issue. Any solution to this?

For context, I am trying to achieve the instagram comment modal. When the modal opens up, the comments are scrollable, with the modal snapped at approximately half the screen but can be expanded when panning on the modal header/handle. Also when it's at the max height and the scrollview is at the top, any downwards drag on the scrollview will snap back the modal back to initial/original modal height.

I don't know if there is any other props combination or if anyone knows how this can achieve kindly comment here.


Thanks 🙏🏽

**Comment by simon-abbott** [comment]
Still broken, do not close.

**Comment by simon-abbott** [comment]
Still not fixed.

**Comment by simon-abbott** [comment]
This issue is still not fixed and should not have been closed. @gorhom please re-open.

**Comment by aledebla03** [comment]
issue still here

**Comment by stefanahman** [comment]
This is a really aggressive bot… still a problem.

**Comment by mvolonnino** [comment]
This is also an issue when using the `BottomSheetModal` wrapping a `NavigationContainer` to allow bottom sheet navigation. Breaks the usage for iOS swipe gestures to be able to swipe back to a previous route.

Need to use the BottomSheetComponents (BottomSheetFlatList) as I utilize the `enableDynamicSizing` prop on the modal to get the correct height for each screen, but when using that component, you can scroll just fine but can't swipe back.

If i use the prop `enableContentPanningGesture={false}` as suggested on the Bottom Sheet Modal, the scrolling breaks on the BottomSheetFlatList, but you do get the swipe gesture back for navigation.

**Anyone have any ideas?**

Need these things from the modal:
- dynamic sizing for each screen as each screen is different heights and the modal is perfect for having the dynamic sizing built it.
- navigation within the bottom sheet modal, which works with the native stack and having the native screen props works with the header back button

Seems like this issue should still be opened as this package states you can utilize bottom sheets with navigation, yet using the components built into the package breaks some of the core native navigation (ios swipe back gesture)

**Comment by dannyhw** [comment]
has anyone got a workaround for this? is this fixed in v5?

**Comment by ArtyEmsee** [comment]
I am having this issue on `4.6.1`. @gorhom Any advice? This issue is years old.

**Comment by Lelouch65428** [comment]
@gorhom I am also having this issue, everything else is working perfectly fine. But this issue is blocking my release. Any advice on this ?

**Comment by Serdnad** [comment]
Adding `enableOverDrag={false}>` like @keithluchtel solved this for me! Even with `enablePanDownToClose={true}`.

**Comment by dniccum** [comment]
This is still an issue.

**Comment by MorganTrudeau** [comment]
I would consider this a bug because the prop references the pan gesture and not the scroll. Also it works great in android. However since BottomSheet Scrollables (ex BottomSheetScrollView) are used to achieve a smooth transition between scroll and pan it seems using BottomSheetScrollView with pan disabled seems unnecessary. For now I will do the following:

```
  const panEnabled = modalProps?.enablePanDownToClose;

  const ScrollComponent = useMemo(
    () => (panEnabled ? BottomSheetScrollView : ScrollView),
    [panEnabled],
  );
  ```

**Comment by poupsipoups** [comment]
Hey this is still an issue on this :/

**Comment by htgabriel** [comment]
This is still an issue :(

**Comment by adammonteil** [comment]
still an issue !!  @gorhom it's been more than 3 years please do something ???

**Comment by gorhom** [comment]
This should been fixed with v5, please test it and let me know

**Comment by adammonteil** [comment]
mb i wasn't aware of it, it's working, i apologize 😅

**Comment by stefanahman** [comment]
@gorhom would it be possible to refer to the change that fixes this problem? 🙏🏻

**Comment by gorhom** [comment]
https://github.com/gorhom/react-native-bottom-sheet/commit/2962a2d5326e517a48fe11d0e0d762beacca890d

**Comment by liaugust** [comment]
@gorhom It still isn’t working as expected, even in your own example

![Image](https://github.com/user-attachments/assets/96fb7cb6-beb1-4344-8397-8f6a70f41a71)

**Comment by simon-abbott** [comment]
@liaugust that seems like a different issue to me. This bug was about not being able to scroll at all, not about the bounds being incorrect.
