### ISSUE TITLE
[v4] Cannot read property toString of undefined

### ISSUE THREAD

**Issue by tsvetann** [gorhom/react-native-scroll-bottom-sheet#819]
# Bug

After upgrading from 4 to 4.1.5 I get this error message: `Cannot read property toString of undefined`.
Tried to debug a bit and it seems like in `utils.js` there is one exported function below:

```javascript
// builds one big hash from multiple worklets' hashes
export function buildWorkletsHash(handlers) {
    return Object.values(handlers).reduce((acc, worklet) => 
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    acc + worklet.__workletHash.toString(), '');
}
```
`worklet.__workletHash.toString()` seems to be undefined for me. Console logging `worklet.__workletHash` gives me `[Function onEnd]`

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet            | 4.1.5   |
| react-native                    | 0.66.4  |
| react-native-reanimated         | 2.3.1   |
| react-native-gesture-handler    | 2.2.0   | also tried with 1.10.3

## Steps To Reproduce

1. Current version 4
2. Upgrade to 4.1.5

Describe what you expected to happen:

1. Eveything to work out of the box as with the prev installed version

## Reproducible sample code

Please note that everything was working out just perfect until I decided to upgrade the package. I understand this might not be an issue with the lib itself so I will appreciate any ideas and hints on how to debug further to find out what the issue is. 

![Screenshot_20220222-130652.jpg](https://user-images.githubusercontent.com/2565891/155120404-37f77ff7-851e-4089-80f7-22bbc571920a.jpg)

Thanks

**Comment by thespacemanatee** [comment]
I'm getting this too on the web

Edit:
Try this: https://github.com/gorhom/react-native-bottom-sheet/issues/11#issuecomment-916025454

Worked for me

**Comment by tsvetann** [comment]
Thanks @thespacemanatee but I am not using expo

**Comment by thespacemanatee** [comment]
> Thanks @thespacemanatee but I am not using expo

If you scrolled a little you would have seen the non-expo solution: 
https://github.com/gorhom/react-native-bottom-sheet/issues/11#issuecomment-1012062676

**Comment by tsvetann** [comment]
Hi @thespacemanatee I tried the non-expo solution but isn't working either. Is it expected to work for react native mobile as the issue you pointed me to is solving it for RN web?

**Comment by rahmanharoon** [comment]
Any update on this..??

**Comment by tsvetann** [comment]
@gorhom could you possibly help us to use this very good looking library. Thanks mate

**Comment by tsvetann** [comment]
ok I figured it out. In my case was a wrong metro config. I tried to customise the metro config to be able to load .cjs modules which i needed for the new apollo client version but in apollo docs they provided a metro.config.js patch that broke bottom sheet for me

**Comment by vtrrsl** [comment]
@tsvetann Did you get this lib working together with the new apollo version? If so, would you mind sharing the metro.config.js?

**Comment by tsvetann** [comment]
@vtrrsl yes I made it work for the new apollo version. the problem is the config apollo provided is not working well for RN.

Here is how I fixed it:

```javascript
// workaround for v3.5.0
// https://github.com/apollographql/apollo-client/releases
const defaultSourceExts =
  require('metro-config/src/defaults/defaults').sourceExts;
module.exports = {
  transformer: {
    getTransformOptions: () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
  resolver: {
    sourceExts: process.env.RN_SRC_EXT
      ? [...process.env.RN_SRC_EXT.split(',').concat(defaultSourceExts), 'cjs'] // <-- cjs added here
      : [...defaultSourceExts, 'cjs'], // <-- cjs added here
  },
};
```

Hope it helps you

**Comment by tsvetann** [comment]
ofc don't forget to clear the metro cache

**Comment by vtrrsl** [comment]
@tsvetann Thanks a lot for the answer, appreciate it! Works now :)

**Comment by crizzis** [comment]
I'm getting the exact same issue, I simply initialized a new Expo TS project, ran `expo install @gorhom/bottom-sheet@^4.1 react-native-reanimated react-native-gesture-handler`, and replaced `App.tsx` with [this content](https://gorhom.github.io/react-native-bottom-sheet/usage) (I'm using Expo 44 FYI). 

I tried applying [this solution](https://github.com/gorhom/react-native-bottom-sheet/issues/11#issuecomment-1072756577), but: 

- I needed to downgrade to Expo 43
- After that, the bottom sheet would just appear partially visible at the bottom of the screen, with no possibility to actually expand it

@gorhom Any chance to reopen this ticket?

**Comment by jahglow** [comment]
I couldn't make it work. I cannot completely remove metro.config.js because I use NX and svg-transformer. Nx is a monorepo and does path resolution base on tsconfigs. no ide how to make it work, tried all possible solutions even excluding svg-transformer with no luck
```ts
const { withNxMetro } = require('@nrwl/react-native');
const { getDefaultConfig } = require('metro-config');

const requiredExts = ['svg', 'cjs', 'mjs'];

module.exports = (async () => {
  const defaultConfig = await getDefaultConfig();
  const {
    resolver: { assetExts, resolverMainFields, sourceExts },
  } = defaultConfig;

  const RN_SRC_EXT = process.env.RN_SRC_EXT;
  const result = withNxMetro(
    {
      transformer: {
        getTransformOptions: async () => ({
          transform: {
            experimentalImportSupport: false,
            inlineRequires: true,
          },
        }),
        babelTransformerPath: require.resolve('react-native-svg-transformer'),
      },
      resolver: {
        assetExts: assetExts.filter(ext => ext !== 'svg'),
        sourceExts: RN_SRC_EXT
          ? [...RN_SRC_EXT.split(',').concat(sourceExts), ...requiredExts]
          : [...sourceExts, ...requiredExts],
        resolverMainFields: ['sbmodern', 'dev', ...resolverMainFields],
      },
    },
    {
      // Change this to true to see debugging info.
      // Useful if you have issues resolving modules
      debug: false,
      // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx'
      extensions: requiredExts,
    },
  );
  return result;
})();

```

**Comment by nlindroos** [comment]
Got the same error in Jest. Fixed that and a few other errors with the following mock
```js
jest.mock('react-native-reanimated', () => ({
  ...require('react-native-reanimated/mock'),
  makeMutable: jest.fn(),
  useWorkletCallback: jest.fn().mockReturnValue(() => {}),
}))
```

**Comment by jahglow** [comment]
Anyone stumbling over this and losing it over debugging and various solutions that never worked, your last resort would be [this comment](https://github.com/software-mansion/react-native-reanimated/issues/3049#issuecomment-1117281665)

**Comment by AbreezaSaleem** [comment]
I just installed this package following the instructions [here](https://gorhom.github.io/react-native-bottom-sheet/) and tried adding the `BottomSheet` component following the tutorial [here](https://gorhom.github.io/react-native-bottom-sheet/usage) and I immediately got this error... Can we please get an official fix for this because I am unable to use this library and it's great and I'd really like to use it.

**Comment by AbreezaSaleem** [comment]
> Anyone stumbling over this and losing it over debugging and various solutions that never worked, your last resort would be [this comment](https://github.com/software-mansion/react-native-reanimated/issues/3049#issuecomment-1117281665)

I followed the steps you mention [here](https://github.com/software-mansion/react-native-reanimated/issues/3049#issuecomment-1129740336) but I am still getting this error.

**Comment by tindn** [comment]
@AbreezaSaleem Just ran into this issue and resolved by doing this step during the installation guide for `react-native-reanimated` https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#babel-plugin

Maybe this will help you

**Comment by novellizator** [comment]
I downgraded to v2 for this very reason, that works well out of the box :)

**Comment by CleissonVieira** [comment]
I can't solve this case

v4
![image](https://user-images.githubusercontent.com/29258164/174795171-b232e126-8581-4eb8-b3a3-d0eae7d4d797.png)
![image](https://user-images.githubusercontent.com/29258164/174795249-7a14a3d8-fc7f-4b24-969d-4d558154c84a.png)

![image](https://user-images.githubusercontent.com/29258164/174795103-8792f704-78ba-4103-9a40-237ef6164641.png)
![image](https://user-images.githubusercontent.com/29258164/174795135-74c236c1-03f3-46ea-ac30-e52ea4703e82.png)

**Comment by chubo274** [comment]
> @vtrrsl yes I made it work for the new apollo version. the problem is the config apollo provided is not working well for RN.
> 
> Here is how I fixed it:
> 
> ```js
> // workaround for v3.5.0
> // https://github.com/apollographql/apollo-client/releases
> const defaultSourceExts =
>   require('metro-config/src/defaults/defaults').sourceExts;
> module.exports = {
>   transformer: {
>     getTransformOptions: () => ({
>       transform: {
>         experimentalImportSupport: false,
>         inlineRequires: true,
>       },
>     }),
>   },
>   resolver: {
>     sourceExts: process.env.RN_SRC_EXT
>       ? [...process.env.RN_SRC_EXT.split(',').concat(defaultSourceExts), 'cjs'] // <-- cjs added here
>       : [...defaultSourceExts, 'cjs'], // <-- cjs added here
>   },
> };
> ```
> 
> Hope it helps you

i was tried this. but it still get the same error.

i'm using bottom sheet v4, gesture-handler v2, reanimated v2

**Comment by rodrigovive** [comment]
> I'm getting this too on the web
> 
> Edit: Try this: [#11 (comment)](https://github.com/gorhom/react-native-bottom-sheet/issues/11#issuecomment-916025454)
> 
> Worked for me

Works for me with the [v4.3.2](https://github.com/gorhom/react-native-bottom-sheet/releases/tag/v4.3.2)
On  web storybook and web.

**Comment by matheusAle** [comment]
I have this

> > @vtrrsl yes I made it work for the new apollo version. the problem is the config apollo provided is not working well for RN.
> > Here is how I fixed it:
> > ```js
> > // workaround for v3.5.0
> > // https://github.com/apollographql/apollo-client/releases
> > const defaultSourceExts =
> >   require('metro-config/src/defaults/defaults').sourceExts;
> > module.exports = {
> >   transformer: {
> >     getTransformOptions: () => ({
> >       transform: {
> >         experimentalImportSupport: false,
> >         inlineRequires: true,
> >       },
> >     }),
> >   },
> >   resolver: {
> >     sourceExts: process.env.RN_SRC_EXT
> >       ? [...process.env.RN_SRC_EXT.split(',').concat(defaultSourceExts), 'cjs'] // <-- cjs added here
> >       : [...defaultSourceExts, 'cjs'], // <-- cjs added here
> >   },
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope it helps you
> 
> i was tried this. but it still get the same error.
> 
> i'm using bottom sheet v4, gesture-handler v2, reanimated v2

@chubo274 any updates?

**Comment by numandev1** [comment]
`import BottomSheet from '@gorhom/bottom-sheet/src';` import like this fixes the issue

**Comment by matheusAle** [comment]
thanks! I found it another day hehe
this bug gave me a headache

**Comment by christiaankreeftmeijer** [comment]
> https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#babel-plugin

Thanks! This fixed it for me. Did add the plugin before but needed to clear the cache too.

**Comment by betanyeli** [comment]
> `import BottomSheet from '@gorhom/bottom-sheet/src';` import like this fixes the issue

it works for us <3<3 ❤️ gracias señor ❤️❤️❤️❤️❤️❤️❤️❤️🎉🎉🎉🎉🇨🇱🇨🇱🇨🇱🇨🇱

**Comment by johnstew** [comment]
Still seeing this - none of these solutions worked.

**Comment by VictorPulzz** [comment]
> `import BottomSheet from '@gorhom/bottom-sheet/src';` import like this fixes the issue

Yes this fix, but typescript validation is broken
<img width="471" alt="image" src="https://user-images.githubusercontent.com/23406402/233871460-c693fe56-ad9f-4d78-89f1-f22be345de23.png">

**Comment by mahshid22** [comment]
Hi 
I have same error and test all solution but no progress...
`TypeError: Cannot read properties of undefined (reading 'toString')
    at utils.js:1:1
    at Array.reduce (<anonymous>)
    at buildWorkletsHash (utils.js:1:1)
    at buildDependencies (utils.js:1:1)
    at useHandler (utils.js:1:1)
    at useAnimatedGestureHandler (useAnimatedGestureHandler.js:1:1)
    at useGestureHandler (useGestureHandler.js:3:1)
    at BottomSheetGestureHandlersProvider (BottomSheetGestureHandlersProvider.js:21:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)

`
PS: I wanna use react-native-bottom-sheet on storybook(web) and i do NOT use expo
i did all the steps in the  doc include adding plugins and so on
on android every things work fine
could anybody help me?

**Comment by jmejiamu** [comment]
Hello every 
Package: 
```shell
"@gorhom/bottom-sheet": "^4.5.1",
"react-native-gesture-handler": "^2.13.1",
"react-native-reanimated": "^3.5.4",
```
I am getting this error in React native cli. I am following this [Bottom Sheet Modal](https://gorhom.github.io/react-native-bottom-sheet/modal/usage/)

```shell
ERROR  TypeError: Cannot read property 'BottomSheetModalProvider' of undefined

This error is located at:
    in BottomSheet (created by unboundStoryFn)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by unboundStoryFn)
    in unboundStoryFn (created by StoryView)
    in RCTView (created by View)
    in View (created by StoryView)
    in StoryView (created by OnDeviceUI)
    in RCTView (created by View)
    in View (created by Preview)
    in RCTView (created by View)
    in View
    in Unknown (created by Preview)
    in Preview (created by OnDeviceUI)
    in RCTView (created by View)
    in View
    in Unknown (created by OnDeviceUI)
    in RCTView (created by View)
    in View (created by AbsolutePositionedKeyboardAwareView)
    in RCTView (created by View)
    in View (created by AbsolutePositionedKeyboardAwareView)
    in AbsolutePositionedKeyboardAwareView (created by OnDeviceUI)
    in RCTView (created by View)
    in View (created by KeyboardAvoidingView)
    in KeyboardAvoidingView (created by OnDeviceUI)
    in RCTView (created by View)
    in View (created by emotion(View))
    in emotion(View) (created by OnDeviceUI)
    in OnDeviceUI
    in ThemeProvider2
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider
    in Unknown
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in WalkSmart(RootComponent), js engine: hermes
 LOG  [TypeError: Cannot read property 'BottomSheetModalProvider' of undefined]
 ERROR  Error rendering story 'buttonsheet--basic':
 ERROR  [TypeError: Cannot read property 'BottomSheetModalProvider' of undefined]
```
 
 IMPLEMENTATION:
 ```typescript
//BottomSheet.tsx
import React, {useRef} from 'react';
import {View, Text, StyleSheet, Button} from 'react-native';

import {BottomSheetModal, BottomSheetModalProvider} from '@gorhom/bottom-sheet';

const BottomSheet = () => {
  const bottomSheetRef = useRef<BottomSheetModal>(null);

  const snapPoints = ['25%'];

  const handlePressModal = () => {
    bottomSheetRef.current?.present();
  };

  return (
    <BottomSheetModalProvider>
      <View style={styles.container}>
        <Button title="Show Modal" onPress={handlePressModal} />
        <BottomSheetModal
          ref={bottomSheetRef}
          index={0}
          snapPoints={snapPoints}>
          <View>
            <Text>Awesome 🎉</Text>
          </View>
        </BottomSheetModal>
      </View>
    </BottomSheetModalProvider>
  );
};

export default BottomSheet;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
    backgroundColor: 'grey',
  },
});
```
STORYBOOK:
```typescript

import React from 'react';
import {View, Text} from 'react-native';
import BottomSheet from './BottomSheet';
import {GestureHandlerRootView} from 'react-native-gesture-handler';

const BottomSheetMeta = {
  title: 'ButtonSheet',
  component: BottomSheet,
  decorators: [
    Story => (
      <GestureHandlerRootView style={{flex: 1}}>
        <BottomSheet />
      </GestureHandlerRootView>
    ),
  ],
};

export default BottomSheetMeta;
export const Basic = {};
```
<img width="339" alt="Screenshot 2023-10-07 at 3 07 35 PM" src="https://github.com/gorhom/react-native-bottom-sheet/assets/27458911/8c3b2859-35e5-4cbb-8760-bd51447cb9f0">


I just wonder if I am missing something here? or I am implementing this incorrectly?

**Comment by pro100user19** [comment]
> I couldn't make it work. I cannot completely remove metro.config.js because I use NX and svg-transformer. Nx is a monorepo and does path resolution base on tsconfigs. no ide how to make it work, tried all possible solutions even excluding svg-transformer with no luck
> 
> ```ts
> const { withNxMetro } = require('@nrwl/react-native');
> const { getDefaultConfig } = require('metro-config');
> 
> const requiredExts = ['svg', 'cjs', 'mjs'];
> 
> module.exports = (async () => {
>   const defaultConfig = await getDefaultConfig();
>   const {
>     resolver: { assetExts, resolverMainFields, sourceExts },
>   } = defaultConfig;
> 
>   const RN_SRC_EXT = process.env.RN_SRC_EXT;
>   const result = withNxMetro(
>     {
>       transformer: {
>         getTransformOptions: async () => ({
>           transform: {
>             experimentalImportSupport: false,
>             inlineRequires: true,
>           },
>         }),
>         babelTransformerPath: require.resolve('react-native-svg-transformer'),
>       },
>       resolver: {
>         assetExts: assetExts.filter(ext => ext !== 'svg'),
>         sourceExts: RN_SRC_EXT
>           ? [...RN_SRC_EXT.split(',').concat(sourceExts), ...requiredExts]
>           : [...sourceExts, ...requiredExts],
>         resolverMainFields: ['sbmodern', 'dev', ...resolverMainFields],
>       },
>     },
>     {
>       // Change this to true to see debugging info.
>       // Useful if you have issues resolving modules
>       debug: false,
>       // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx'
>       extensions: requiredExts,
>     },
>   );
>   return result;
> })();
> ```

Has anyone fixed this using nx with **svg-transformer** and **metro**?

**Comment by Praisecodes** [comment]
> `import BottomSheet from '@gorhom/bottom-sheet/src';` import like this fixes the issue

This works for me!! ❤️
